// src/utils/theme.js
export const COLORS = {
  bg: '#0F0F14',
  bgCard: '#1A1A24',
  bgElevated: '#22222F',
  bgInput: '#12121A',
  accent: '#7C6FE0',
  accentLight: '#9D93E8',
  accentDim: '#2A2650',
  teal: '#1DB584',
  tealDim: '#0D3D2D',
  amber: '#F0A500',
  amberDim: '#3A2800',
  red: '#E84B4B',
  redDim: '#3A1212',
  textPrimary: '#FFFFFF',
  textSecondary: '#8888A0',
  textTertiary: '#55556A',
  border: '#2A2A3A',
  borderLight: '#33334A',
};

export const FONTS = {
  regular: { fontWeight: '400' },
  medium: { fontWeight: '500' },
  semibold: { fontWeight: '600' },
  bold: { fontWeight: '700' },
};

export const RADIUS = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  full: 999,
};

export const SPLITS = [
  {
    id: 'ppl',
    name: 'PPL',
    full: 'Push Pull Legs',
    days: 6,
    schedule: ['Push', 'Pull', 'Legs', 'Push', 'Pull', 'Legs', 'Rest'],
    icon: '🔄',
    desc: '6-day · Chest, back & legs',
  },
  {
    id: 'bro',
    name: 'Bro Split',
    full: 'Classic Bro Split',
    days: 5,
    schedule: ['Chest', 'Back', 'Shoulders', 'Arms', 'Legs', 'Rest', 'Rest'],
    icon: '💪',
    desc: '5-day · One muscle group/day',
  },
  {
    id: 'ul',
    name: 'Upper/Lower',
    full: 'Upper Lower Split',
    days: 4,
    schedule: ['Upper', 'Lower', 'Rest', 'Upper', 'Lower', 'Rest', 'Rest'],
    icon: '⚡',
    desc: '4-day · Great for beginners',
  },
  {
    id: 'fullbody',
    name: 'Full Body',
    full: 'Full Body',
    days: 3,
    schedule: ['Full Body', 'Rest', 'Full Body', 'Rest', 'Full Body', 'Rest', 'Rest'],
    icon: '🏋️',
    desc: '3-day · Efficient & balanced',
  },
  {
    id: 'arnold',
    name: 'Arnold Split',
    full: 'Arnold Split',
    days: 6,
    schedule: ['Chest & Back', 'Shoulders & Arms', 'Legs', 'Chest & Back', 'Shoulders & Arms', 'Legs', 'Rest'],
    icon: '🏆',
    desc: '6-day · Arnold\'s signature program',
  },
];

export const EXERCISE_LIBRARY = {
  Push: [
    { name: 'Bench Press', sets: 4, reps: '6-8', muscle: 'Chest' },
    { name: 'Overhead Press', sets: 4, reps: '8-10', muscle: 'Shoulders' },
    { name: 'Incline Dumbbell Press', sets: 3, reps: '10-12', muscle: 'Upper Chest' },
    { name: 'Cable Fly', sets: 3, reps: '12-15', muscle: 'Chest' },
    { name: 'Lateral Raise', sets: 4, reps: '15-20', muscle: 'Shoulders' },
    { name: 'Tricep Pushdown', sets: 3, reps: '12-15', muscle: 'Triceps' },
    { name: 'Overhead Tricep Extension', sets: 3, reps: '10-12', muscle: 'Triceps' },
  ],
  Pull: [
    { name: 'Deadlift', sets: 4, reps: '5-6', muscle: 'Back' },
    { name: 'Pull-Ups', sets: 4, reps: '6-10', muscle: 'Lats' },
    { name: 'Barbell Row', sets: 4, reps: '8-10', muscle: 'Mid Back' },
    { name: 'Lat Pulldown', sets: 3, reps: '10-12', muscle: 'Lats' },
    { name: 'Face Pull', sets: 3, reps: '15-20', muscle: 'Rear Delts' },
    { name: 'Barbell Curl', sets: 3, reps: '10-12', muscle: 'Biceps' },
    { name: 'Hammer Curl', sets: 3, reps: '12-15', muscle: 'Biceps' },
  ],
  Legs: [
    { name: 'Squat', sets: 4, reps: '6-8', muscle: 'Quads' },
    { name: 'Romanian Deadlift', sets: 4, reps: '8-10', muscle: 'Hamstrings' },
    { name: 'Leg Press', sets: 3, reps: '10-12', muscle: 'Quads' },
    { name: 'Leg Curl', sets: 3, reps: '12-15', muscle: 'Hamstrings' },
    { name: 'Calf Raise', sets: 4, reps: '15-20', muscle: 'Calves' },
    { name: 'Bulgarian Split Squat', sets: 3, reps: '10-12', muscle: 'Quads' },
  ],
  Chest: [
    { name: 'Bench Press', sets: 5, reps: '6-8', muscle: 'Chest' },
    { name: 'Incline Press', sets: 4, reps: '8-10', muscle: 'Upper Chest' },
    { name: 'Dumbbell Fly', sets: 3, reps: '12-15', muscle: 'Chest' },
    { name: 'Cable Crossover', sets: 3, reps: '15', muscle: 'Chest' },
    { name: 'Push-Ups', sets: 3, reps: '20', muscle: 'Chest' },
  ],
  Back: [
    { name: 'Deadlift', sets: 4, reps: '5-6', muscle: 'Back' },
    { name: 'Pull-Ups', sets: 4, reps: '6-10', muscle: 'Lats' },
    { name: 'Bent Over Row', sets: 4, reps: '8-10', muscle: 'Mid Back' },
    { name: 'Seated Cable Row', sets: 3, reps: '12', muscle: 'Mid Back' },
    { name: 'T-Bar Row', sets: 3, reps: '10-12', muscle: 'Back' },
  ],
  Shoulders: [
    { name: 'Overhead Press', sets: 5, reps: '6-8', muscle: 'Shoulders' },
    { name: 'Arnold Press', sets: 4, reps: '10-12', muscle: 'All Delts' },
    { name: 'Lateral Raise', sets: 4, reps: '15-20', muscle: 'Side Delts' },
    { name: 'Front Raise', sets: 3, reps: '12-15', muscle: 'Front Delts' },
    { name: 'Rear Delt Fly', sets: 3, reps: '15', muscle: 'Rear Delts' },
  ],
  Arms: [
    { name: 'Barbell Curl', sets: 4, reps: '10-12', muscle: 'Biceps' },
    { name: 'Hammer Curl', sets: 3, reps: '12-15', muscle: 'Biceps' },
    { name: 'Tricep Pushdown', sets: 4, reps: '12-15', muscle: 'Triceps' },
    { name: 'Skull Crushers', sets: 3, reps: '10-12', muscle: 'Triceps' },
    { name: 'Concentration Curl', sets: 3, reps: '12', muscle: 'Biceps' },
  ],
  Upper: [
    { name: 'Bench Press', sets: 4, reps: '8-10', muscle: 'Chest' },
    { name: 'Barbell Row', sets: 4, reps: '8-10', muscle: 'Back' },
    { name: 'Overhead Press', sets: 3, reps: '8-10', muscle: 'Shoulders' },
    { name: 'Pull-Ups', sets: 3, reps: '6-10', muscle: 'Lats' },
    { name: 'Dumbbell Curl', sets: 3, reps: '12', muscle: 'Biceps' },
    { name: 'Tricep Extension', sets: 3, reps: '12', muscle: 'Triceps' },
  ],
  Lower: [
    { name: 'Squat', sets: 4, reps: '6-8', muscle: 'Quads' },
    { name: 'Romanian Deadlift', sets: 4, reps: '8-10', muscle: 'Hamstrings' },
    { name: 'Leg Press', sets: 3, reps: '10-12', muscle: 'Quads' },
    { name: 'Leg Curl', sets: 3, reps: '12-15', muscle: 'Hamstrings' },
    { name: 'Calf Raise', sets: 4, reps: '15-20', muscle: 'Calves' },
  ],
  'Full Body': [
    { name: 'Squat', sets: 3, reps: '8-10', muscle: 'Quads' },
    { name: 'Bench Press', sets: 3, reps: '8-10', muscle: 'Chest' },
    { name: 'Barbell Row', sets: 3, reps: '8-10', muscle: 'Back' },
    { name: 'Overhead Press', sets: 3, reps: '8-10', muscle: 'Shoulders' },
    { name: 'Romanian Deadlift', sets: 3, reps: '10-12', muscle: 'Hamstrings' },
  ],
  'Chest & Back': [
    { name: 'Bench Press', sets: 4, reps: '8-10', muscle: 'Chest' },
    { name: 'Deadlift', sets: 4, reps: '6-8', muscle: 'Back' },
    { name: 'Pull-Ups', sets: 3, reps: '8-10', muscle: 'Lats' },
    { name: 'Incline Press', sets: 3, reps: '10-12', muscle: 'Upper Chest' },
    { name: 'Cable Row', sets: 3, reps: '12', muscle: 'Mid Back' },
  ],
  'Shoulders & Arms': [
    { name: 'Overhead Press', sets: 4, reps: '8-10', muscle: 'Shoulders' },
    { name: 'Lateral Raise', sets: 4, reps: '15-20', muscle: 'Side Delts' },
    { name: 'Barbell Curl', sets: 4, reps: '10-12', muscle: 'Biceps' },
    { name: 'Tricep Pushdown', sets: 4, reps: '12-15', muscle: 'Triceps' },
    { name: 'Hammer Curl', sets: 3, reps: '12', muscle: 'Biceps' },
  ],
};
